# Generated by Django 5.0.3 on 2024-03-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_registration_is_active_alter_registration_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Others', 'Others'), ('Female', 'Female')], default='Male', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
